# Generated by Django 4.2.4 on 2024-02-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_instructor_student_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("STUDENT", "Student"),
                    ("INSTRUCTOR", "Instructor"),
                ],
                default="STUDENT",
                help_text="Custom user roles",
                max_length=10,
            ),
        ),
    ]
